### ISSUE TITLE
[3.x] Replace Guzzle client with Laravel HTTP Client

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#102]
Replace the Guzzle client with the built in [HTTP client](https://laravel.com/docs/8.x/http-client) provided by the Laravel framework.

**Comment by craigpaul** [comment]
Just tagged `v3.0.0-RC1` which is utilizing the built-in HTTP client. Please feel free to take it for a spin and send in any issues / PRs needed before a full release can take place 👍
