### ISSUE TITLE
Testing postmark TLS configuration changes

### ISSUE THREAD

**Issue by GabrielBuragev** [coconutcraig/laravel-postmark#122]
## Detailed description

I am trying to figure out how to test the upcoming tls configuration changes on the postmark api : https://postmarkapp.com/updates/upcoming-tls-configuration-changes-for-api-users-action-may-be-required

## Context

These changes may affect the application’s ability to continue to send mail through Postmark.

## Your environment

- Laravel Postmark Version: 2.6
- Laravel Version: 5.8.37
- PHP Version: 7.1.3

**Comment by craigpaul** [comment]
Hey @GabrielBuragev, can you take a look at the linked PR and let me know if that can solve your issue 👍

**Comment by mvdnbrk** [comment]
Make sure your infrastructure is up to date and this change won't affect you.

- Do not use TLSv1 anymore, this is deprecated
- Don't use old/weak ciphers
- HSTS headers on Postmarks end will not affect connectivity

**Comment by GabrielBuragev** [comment]
> Hey @GabrielBuragev, can you take a look at the linked PR and let me know if that can solve your issue

This PR will be sufficient for testing. Thanks for the quick resolve !
