### ISSUE TITLE
Inline attachments not working

### ISSUE THREAD

**Issue by djurovicigoor** [coconutcraig/laravel-postmark#126]
I am trying to add an inline attachment inside my blade email file.

$message->embed(public_path('img/mail/logo.png')) or $message->embed(asset('img/mail/logo.png')) but only what I got in final email is data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7

I also tried the official wildbit library recommended by Laravel doc (https://github.com/wildbit/swiftmailer-postmark) and that works fine. I need to continue using this package because I can get MessageID.

- Laravel Postmark Version: v2.10.1
- Laravel Version: 8.53.0
- PHP Version: 7.4.16

**Comment by craigpaul** [comment]
Hey @djurovicigoor, that's strange, unless there's some weird conflict with this package, I'm not exactly sure how it could affect the rendering of a blade view. I'll take a look and see what I can figure out.

**Comment by craigpaul** [comment]
@djurovicigoor I found the issue. I wasn't handling the attachments fully inside of the `getAttachments` function. Will have a fix released pretty quick here. Thanks for finding that! 👍
