### ISSUE TITLE
[3.x] Preparing for Symfony 6.0 & Laravel 9.0

### ISSUE THREAD

**Issue by joostdebruijn** [coconutcraig/laravel-postmark#131]
## Detailed description

The release of Laravel 9.0 is scheduled for January 2022 and it ships with Symfony 6.0. Swift Mailer is replaced by Symfony Mailer.

Relevant pages and PR's to have a look at:
- https://symfony.com/blog/the-end-of-swiftmailer
- laravel/framework#38481
- laravel/docs#7454

## Context

This project provide some features I like which are not present in the Symfony Postmark bridge, most notably sending mails via templates. It is not likely that the Symfony Postmark Bridge will implement this functionality in their project for obvious reasons, looking at a similar case for Mandrill (symfony/symfony#37612).

## Possible implementation

The changes in Symfony 6.0 and Laravel 9.0 are not backwards compatible and require a serious rewrite of this project (for example run the tests in https://github.com/joostdebruijn/laravel-postmark/tree/3.x). It may be interesting to have a look at the Symfony Postmark Bridge (https://github.com/symfony/postmark-mailer) and extend it where necessary to achieve feature parity with the module at this moment. This reduces maintance on this module while keeping the extra functionality.

Of course I'm very happy to help, but before spending time on this I would like to know what the maintainer of this package thinks of the upcoming changes and the future of this project.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

- Laravel Postmark Version: 3.0.0?
- Laravel Version: >= 9.0.0
- PHP Version: >= 8.0.0

**Comment by craigpaul** [comment]
Hey @joostdebruijn, I'm thinking that v3 of this project could be a complete rewrite that supports Laravel 9 + Symfony Mailer exclusively. I'll add this to the v3 milestone. I'm hoping to have time for this over the holidays / in the new year, but I'll gladly accept PRs for any of the v3 milestone items.

**Comment by Jubeki** [comment]
@craigpaul What about making this package a wrapper around the [Symfony Postmark-Mailer](https://github.com/symfony/postmark-mailer)?

You can also take a look at The [Symfony Mailer Docs](https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport) for more information.

Laravel 9 will also use different Symfony mailer under the hood. Maybe this will make some things simpler for upgrading.

**Comment by craigpaul** [comment]
I got a small start on v3 tonight. Ended up deciding on a full-on rewrite, so I'll be posting some updates within this (and other relevant issues) as I go. The symfony/mailer is a bit strange, but it's starting to make more sense the further I get into this 👍

**Comment by joostdebruijn** [comment]
Nice @craigpaul! If there is something I can help with, please let me know.

**Comment by craigpaul** [comment]
Just tagged `v3.0.0-RC1` which addresses the upgrade from `swiftmailer/swiftmailer` to `symfony/mailer` in Laravel 9.0. Please feel free to take it for a spin and send in any issues / PRs needed before a full release can take place 👍

**Comment by joostdebruijn** [comment]
@craigpaul I gave it a spin in a separate testproject and the implementation is looking great. Nice work!
