### ISSUE TITLE
laravel 9 support

### ISSUE THREAD

**Issue by hai-shift** [coconutcraig/laravel-postmark#138]
i try to update to laravel 9
but i can׳t :(

**Comment by craigpaul** [comment]
Hey @hai-shift, can you provide more details and/or a reproduction of the issue(s) you're experiencing. Laravel 9 has been out for many months now and I've personally been using this library on a couple of different Laravel 9 apps (both upgraded to and new).

**Comment by hai-shift** [comment]
in my compoer: "coconutcraig/laravel-postmark": "^2.10",  


Problem 1
    - Conclusion: don't install coconutcraig/laravel-postmark 2.11.x-dev (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark 2.x-dev (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.0 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.1 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.2 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.0 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.1 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.2 (conflict analysis result)
    - illuminate/mail[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
    - Root composer.json requires coconutcraig/laravel-postmark ^2.10 -> satisfiable by coconutcraig/laravel-postmark[v2.10.0, ..., 2.x-dev].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)

**Comment by craigpaul** [comment]
Can you post your entire `composer.json` file?

**Comment by hai-shift** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.0",
        "actb/blade-github-octicons": "^4.0",
        "coconutcraig/laravel-postmark": "^2.10",
        "fideloper/proxy": "^4.4",
        "fidum/laravel-eloquent-morph-to-one": "^2.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "hisorange/browser-detect": "^4.4",
        "http-interop/http-factory-guzzle": "^1.2",
        "itsmalikjones/blade-iconic": "^1.1",
        "khatabwedaa/blade-css-icons": "^1.0",
        "kirschbaum-development/eloquent-power-joins": "^2.4",
        "laravel/framework": "^9.0",
        "laravel/scout": "^9.3",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "~1.0",
        "livewire/livewire": "^2.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "pestphp/pest-plugin-laravel": "^1.2",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan vendor:publish --force --tag=livewire:assets --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by hai-shift** [comment]
Problem 1
    - Conclusion: don't install coconutcraig/laravel-postmark 2.11.x-dev (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark 2.x-dev (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.0 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.1 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.10.2 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.0 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.1 (conflict analysis result)
    - Conclusion: don't install coconutcraig/laravel-postmark v2.11.2 (conflict analysis result)
    - illuminate/mail[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/mail[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
    - Root composer.json requires coconutcraig/laravel-postmark ^2.10 -> satisfiable by coconutcraig/laravel-postmark[v2.10.0, ..., 2.x-dev].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.10.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.10.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.11.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.19.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - coconutcraig/laravel-postmark 2.10.x-dev requires illuminate/mail ^5.5 || ^6.0 || ^7.0 || ^8.0 -> satisfiable by illuminate/mail[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/mail[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/mail and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by craigpaul** [comment]
Give something like this a try.

```
// Remove package temporarily
composer remove coconutcraig/laravel-postmark;

// Upgrade laravel/framework to ^9.0
composer update laravel/framework -W;

// Re-install package
composer require coconutcraig/laravel-postmark;
```

This isn't really an issue with this library, it's just a pain when upgrading Laravel in general (depending on the composer packages you have installed).
