### ISSUE TITLE
message_stream_id stopped working after last commit 

### ISSUE THREAD

**Issue by nahodnyokoloiduci** [coconutcraig/laravel-postmark#144]
Hello. In the last commit (called "_Adds support for passing in Guzzle options to the Laravel HTTP client_") following line has been added in src/PostmarkServiceProvider.php
_$config = $this->app->make('config');_

unfortunately this overwrites the value of existing _$config_ parameter, therefore few lines further down, the "_$config['message_stream_id']_" is always null. 
If you add _dd($config)_ prior to line 22, you'll see the value of message_stream_id (if defined in mail.php). After line 23 it's undefined because the $config is overwritten.

https://github.com/craigpaul/laravel-postmark/blob/f7fa0aa150c65d513f58f14a693169d0eb2201e0/src/PostmarkServiceProvider.php 

Could you please check? It's easily replicable.
Thanks!

**Comment by craigpaul** [comment]
Hey @nahodnyokoloiduci! Thanks for catching that, totally overlooked it. This is fixed in 72d33e57786fd69ebb4dfc8cb1412fdc79785d01
