### ISSUE TITLE
catch postmark message id in an event listener when message is sent

### ISSUE THREAD

**Issue by xcalabuig** [coconutcraig/laravel-postmark#146]
I'm using this package to send my emails via Postmark (it already works), but I need to store the postmark message ID into DB.
I have an event listener like this, but headers only contains "from","to" and "subject"...

public function handle(MessageSent $event)
    {
          if (isset($event->data['booking'])) {
              $booking = $event->data['booking'];
              $messageId = $event->message->getHeaders()->get('x-pm-message-id')?->getValue() ?? $event->message->getHeaders()->get('message-id')->getName();
              $booking->mailIdentifiers()->create(['message_identifier' => $messageId]);
          }
    }

On my postmarks' account looks like this:
![image](https://github.com/craigpaul/laravel-postmark/assets/93589477/34b2e67a-f8e7-4daf-95c3-9f222ef3f32a)

**Comment by craigpaul** [comment]
Hey @xiaoCreagia, in order to get the message ID from Laravel you will need to add a listener for the `\Illuminate\Mail\Events\MessageSent` event in the `EventServiceProvider`. Eg.

```php
<?php

namespace App\Providers;

use App\Listeners\HandleMessageSent;
use Illuminate\Mail\Events\MessageSent;

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        MessageSent::class => [
            HandleMessageSent::class,
        ],
    ];
}
```

```php
<?php

namespace App\Listeners;

use Illuminate\Mail\Events\MessageSent;

class HandleMessageSent
{
    public function handle(MessageSent $message)
    {
        $messageId = $event->sent->getSymfonySentMessage()->getMessageId();

        // ...
    }
}
```
