### ISSUE TITLE
No hint path defined for [postmark]

### ISSUE THREAD

**Issue by ervshaikh** [coconutcraig/laravel-postmark#147]
[error.txt](https://github.com/user-attachments/files/15847681/error.txt)
The error is :
No hint path defined for [postmark].

Integration Method using: MailMessage with notifiable in Laravel

## Detailed description
I am trying to send an email from existing implementation of laravel notification using postmark email template method.

toMail() which extends by Notification 
![image](https://github.com/craigpaul/laravel-postmark/assets/100956214/61a494f8-7d47-41b9-bfe1-e42ca6532b73)

call from controller using user->notify(with Notification class)
![image](https://github.com/craigpaul/laravel-postmark/assets/100956214/48b3966f-5220-4ad5-a698-c6d415fde8db)

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## In Local environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

- Laravel Postmark Version: v2.11.2
- Laravel Version: 6.20.44
- PHP Version: 7.4.0

**Comment by craigpaul** [comment]
Hey @ervshaikh, do you by chance have this package's service provider in the `extra.laravel.dont-discover` key inside your `composer.json` file? The only way I can reproduce this is by having the service provider be ignored/not run.
