### ISSUE TITLE
Returning the Postmark Message ID

### ISSUE THREAD

**Issue by zoe-edwards** [coconutcraig/laravel-postmark#43]
This is either a question or an enhancement request, or maybe both 😄 

I would like to know the message ID of the email that was just sent.

I’m working on a site where I want our admin users to be able to see the delivery status of emails for each user. Using the webhook I can get a message ID, but I don’t have anyway of matching it up with the sent email.

## Example

An email is sent to someone using Postmark, and the message ID is recoreded in the database. An admin on our site can see that the email was sent, but has not yet been delivered. When there’s a response, the message is updated, so that if it’s bounced (or other), the admin can manually get in contact with the person.

## Context

Any developer that wants to take advantage of the tracking from start-to-finish would find this useful. Useful for important emails (such as legal, buying/selling, recruitment).

## Possible implementation

Just looking at the code here and in Laravel, it looks like the response is either `void` or `$this->numberOfRecipients($message)`, so I don’t know how messy it’ll be to get the message ID from the response.

## My environment

- Laravel Postmark Version: 2.6.0
- Laravel Version: 5.7.28*
- PHP Version: 7.3.10

\* Yes I know it’s on my list.

**Comment by mvdnbrk** [comment]
See [Mail Events](https://laravel.com/docs/5.7/mail#events).

Laravel fires an event when a message has been sent.

You should add a listener for that event and then you will be able to grab the `X-PM-Message-Id` from the headers.

Hope that helps.

**Comment by zoe-edwards** [comment]
Genius! Thanks @mvdnbrk 👍
