### ISSUE TITLE
Setting a custom Message-ID in header for email threading

### ISSUE THREAD

**Issue by arnarstef** [coconutcraig/laravel-postmark#44]
I have a question, 

I am trying to post a "Message-ID" parameter with the headers to the Postmark API so I can thread emails, I also need to post a "In-Reference-To" header parameter as well as "References". This is what I'm currently doing in the build() function of the mailable:

        $this->withSwiftMessage(function (\Swift_Message $message) {
            $msgId = $message->getHeaders()->get('Message-ID');
            $msgId->setId('1571832919_111-test-message@example.org');
            $message->getHeaders()->addTextHeader('X-PM-KeepID', 'true');
        });

When I dump the headers I can see the new Message-ID, but once it reaches Postmark, it doesn't change.

- Laravel Version: 5.8
- PHP Version: 7.3

**Comment by arnarstef** [comment]
I figured out a way to push the headers in by modifying the payload. By adding a 'Headers' key with array values like so:


        $json = [
            'Cc' => $this->getContacts($message->getCc()),
            'Bcc' => $this->getContacts($message->getBcc()),
            'Tag' => $this->getTag($message),
            'Metadata' => $this->getMetadata($message),
            'ReplyTo' => $this->getContacts($message->getReplyTo()),
            'Attachments' => $this->getAttachments($message),
            'Headers' => [
                ['name' => 'Message-ID', 'value' => '<1571832919_111-test-message@example.org>'],
                ['name' => 'X-PM-KeepID', 'value' => 'true']
            ]
        ];

Is there a possibility the ability to insert headers directly will be added in future updates?

**Comment by craigpaul** [comment]
Hey @arnarstef. Interesting problem you have here. I'm not against supporting the ability to add custom headers and would gladly accept a PR on it. How would you see this working if you were to implement it?

@mvdnbrk You have any ideas / suggestions?

**Comment by mvdnbrk** [comment]
Maybe we can achieve this in a similar way as metadata:

```php
$this->withSwiftMessage(function (\Swift_Message $message) {
    $message->getHeaders()->addTextHeader('custom-header-Message-ID', 'value');
});
```

Then we can filter out those custom headers and merge them into the JSON payload.

**Comment by craigpaul** [comment]
@mvdnbrk Thats what I was thinking as well. Thanks!

@arnarstef If you would like to submit a PR with that functionality, that would be fantastic, otherwise I'll try to get around to this as soon as possible 👍

**Comment by mvdnbrk** [comment]
Thinking this over I was asking myself when would you add custom headers?

Most common cases I can think of:
- `In-Reply-To`
- `References`
- `Message-ID`
- `X-*` 

If we filter through these headers and pass them to the JSON payload will make the code easier to read and maintain:

```
$message->getHeaders()->addTextHeader('Message-ID', 'value');
```

instead of

```
$message->getHeaders()->addTextHeader('custom-header-Message-ID', 'value');
````

**Comment by mvdnbrk** [comment]
See PR #48 

- No need to prefix custom headers
- All custom headers will work

@craigpaul What do you think?
