### ISSUE TITLE
Laravel 7 will support multiple mail drivers

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#58]
See https://github.com/laravel/framework/pull/31073

If you stick with `MAIL_DRIVER=postmark` it does not seem to be a problem.

Using `Mail::mailer('postmark')->to(...)` might cause a problem:
https://github.com/craigpaul/laravel-postmark/blob/d2d72000e5ac908664c00478739ebb267484f8f9/src/PostmarkServiceProvider.php#L23-L25

**Comment by craigpaul** [comment]
Seems to me, we'd be safe to remove that check, what's your opinion @mvdnbrk ? I can't remember why it was there in the first place.

**Comment by mvdnbrk** [comment]
That check was added in PR #21

**Comment by mvdnbrk** [comment]
The main change we need to make for L7 compatibility is to on this line:

https://github.com/craigpaul/laravel-postmark/blob/d2d72000e5ac908664c00478739ebb267484f8f9/src/PostmarkServiceProvider.php#L29

`swift.transport` should be replaced with `mail.manager`

@craigpaul Would you prefer to make the package backwards compatible or make the changes needed and bump to v3?

**Comment by mvdnbrk** [comment]
See #67

**Comment by craigpaul** [comment]
Hey @mvdnbrk, I think given the changes Laravel is doing for v7, I'd like to bump to a new major version and drop support for < v7. If theres other stuff you'd like to get in for that major bump, feel free. I'll get to reviewing these soon as I can. Thanks for all the help 👍
