### ISSUE TITLE
Scrutinizer

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#70]
@craigpaul Seems like https://scrutinizer-ci.com/g/coconutcraig/laravel-postmark/ is outdated and the repo is not analyzed anymore by Scrutinizer.

**Comment by craigpaul** [comment]
@mvdnbrk I believe I've got it connected properly again https://scrutinizer-ci.com/g/craigpaul/laravel-postmark/ only thing left would be updating the readme with the correct url I believe
