### ISSUE TITLE
MailMessage Template Laravel 7 Unexpected response

### ISSUE THREAD

**Issue by DevelTwist** [coconutcraig/laravel-postmark#81]
I'm trying to use the MailMessage class to send in postmark template, the configuration is correct but I receive a json as a message to my mailbox.

this is my implementation

![image](https://user-images.githubusercontent.com/22015495/86182711-7411bb00-bafe-11ea-9df1-0832b11c60b5.png)

this is my response

{"__env":{},"app":{"contextual":[]},"id":18999584,"alias":"user-c=
onfirmation","model":{"name":"Usuario","product_name":"Maquillate=
.com","action_url":"https:\/\/dev.maquillate.com\/confirmation","=
login_url":"https:\/\/dev.maquillate.com\/login","username":"Usua=
rio"},"__laravel_notification_id":"02bb8627-5d08-485f-9122-4e7091=
79f8c1","__laravel_notification":"App\\Notifications\\UserConfirm=
ation","__laravel_notification_queued":false,"message":{}}=0D=0A

![image](https://user-images.githubusercontent.com/22015495/86182570-3e6cd200-bafe-11ea-81cf-f451184e6fad.png)

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

- Laravel Postmark Version: 2.8
- Laravel Version: 7.x
- PHP Version: 7.4

**Comment by craigpaul** [comment]
Hey @DevelTwist. When the package detects that it's trying to send a templated email (by checking if the body of the message can be properly JSON decoded), it includes `TemplateId`, `TemplateAlias`, and `TemplateModel` in the request to Postmark. 

Perhaps there is an error happening when it is being decoded? It would look like it's not hitting the `/email/withTemplate` endpoint for some reason. Can you try adding some logging locally and see what does?

**Comment by DevelTwist** [comment]
Let me check

**Comment by keiwerkgvr** [comment]
@craigpaul we couldnt find the issue, we thought about other solution and we fixed it using http package of laravel and postmark api while you can fix this issue.

**Comment by craigpaul** [comment]
I'm not exactly certain I understand the problem. I'm curious if others who use this feature have experienced this. @MatanYadaev have you experienced this?

**Comment by DevelTwist** [comment]
@craigpaul  For some reason the templated method on Transport class is not executing. Unusual

**Comment by craigpaul** [comment]
That's very unusual, never heard of that happening. I'm gonna try a fresh Laravel 7 install to try and reproduce this. If you're able to provide an example repo that can reproduce this problem, that would be very helpful.

**Comment by craigpaul** [comment]
Hey @DevelTwist, I just tried the fresh Laravel 7 install and it worked. I'm going to need to see a repo that can reproduce the error in order to assist any further.

**Comment by craigpaul** [comment]
I'm going to close this for now. If someone can come up with a repository to reproduce the problem, we can take another look 👍
