### ISSUE TITLE
Laravel 7 uses MAIL_MAILER instead of MAIL_DRIVER

### ISSUE THREAD

**Issue by ndeblauw** [coconutcraig/laravel-postmark#85]
## Detailed description

After updating my Laravel app to v7, postmark stopped working. I kept on receiving error code "550 5.7.1". It took me a long time to find where the catch was, as I moved my app to a fresh server at the same time. 

It turned out to be a small detail in the .ENV file, as Laravel 7.0 uses MAIL_MAILER instead of MAIL_DRIVER to select the mailing protocol.

## Possible implementation
Please update your documentation (see screenshot below) so that it mentions also the MAIL_MAILER for Laravel v7 (and higher) option for configuring your postmark driver.

![image](https://user-images.githubusercontent.com/4344869/91060719-94a45000-e62b-11ea-8f4d-bd2036f8cbbc.png)

**Comment by craigpaul** [comment]
Oh, good catch. I can put up a quick fix. Thanks @ndeblauw!
