### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#88]
I think we can remove `travis` and move to Github actions.

Do we still need `scrutinzer`? Does this really add value?
We could move this to a static analyzer like `phpstan` or `psalm` (and run with a GH action).

What do you think @craigpaul ?

**Comment by craigpaul** [comment]
Hey @mvdnbrk, I think that is an excellent idea. No, scrutinizer is not needed if we have something like phpstan in place 😀

**Comment by mvdnbrk** [comment]
Ok, will take a look at it 😄

**Comment by craigpaul** [comment]
All webhooks except Packagist have been removed 👍 Figured we'd get this working and then go forward with Github Actions exclusively

**Comment by craigpaul** [comment]
@mvdnbrk Should we target 2.x? Or do you think it'd be easier to just use Github Actions on 3.x forward?

**Comment by mvdnbrk** [comment]
I have changed the target branch to `2.x`.

I want to make sure all tests are passing with Github actions, also on earlier supported versions.

Once everything is fine we can later merge in non-breaking changes from the `2.x` branch into the `main` branch.

**Comment by craigpaul** [comment]
Merged and rebased to `main` 👍  Thanks @mvdnbrk!
