### ISSUE TITLE
[3.x] Better exceptions

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#89]
Postmark has different response codes when you are sending messages.

For example a `422` response code is returned when you try to send to a recipient that has been marked as inactive.
With the current implementation **all** exceptions on Postmark's end leads to a `GuzzleHttp\Exception\ClientException`.

I am proposing a custom exception which you can catch.
In my use case I can ignore a `422` exception, while a 429 / Rate Limit Exceeded can be catched and I am able to try to send to message again later.

See https://postmarkapp.com/developer/api/overview#response-codes

**Comment by craigpaul** [comment]
I like this idea. If the client exceptions (4xx) all build off of a single base exception, I think this would be a fantastic addition to the package, do you agree? Would we also want specific server exceptions?

**Comment by craigpaul** [comment]
Thinking about it again quickly, perhaps that's (single base exception) not necessary. Let me know your thoughts.

**Comment by mvdnbrk** [comment]
Well depends on the response I guess. In most cases something went wrong on Postmark's end and you would want to try to send the message again.

The `422` is different in my opinion.
Most of the times I get this one is when someone made a typo in their email address.
In my case I can ignore these.

**Comment by craigpaul** [comment]
Just tagged `v3.0.0-RC1` which is throwing a specific exception that passes along the necessary information when a call to Postmark fails. Please feel free to take it for a spin and send in any issues / PRs needed before a full release can take place 👍
