### ISSUE TITLE
[3.x] Message Streams

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#90]
Postmark has introduced [Message Streams](https://postmarkapp.com/message-streams).

I think we should add a way to specify a Stream ID:

- Add the `MessageStream` parameter to the json, which defaults to `outbound`.

See: https://postmarkapp.com/support/article/1207-how-to-create-and-send-through-message-streams

**Comment by craigpaul** [comment]
Now this would be fantastic to support, I agree. Perhaps all these proposed changes this morning could end up being a "reimagining" of sorts? A new major version with some cleanup of some of the older parts of this package.

**Comment by mvdnbrk** [comment]
Perfect! Lets set a milestone for `v3`.

I was just scanning the code. noticed all sorts of redundant docblocks etc, these can be cleaned up as well.

Maybe we can drop support for earlier versions of Laravel, and make use of the HTTP client which is now built in to Laravel (this would require Laravel 7 or later).

Now PHP 8 is on its way we should test against that as well, with a new major release we can increase the minimum PHP version as well.

**Comment by mvdnbrk** [comment]
I am preferring a minimum PHP version of 7.4 so we can take full advantage of typed properties, arrow fuctions etc.

**Comment by craigpaul** [comment]
I love and am on-board with all these ideas 👍. I'll set up the project and milestone stuff later today (still a bit early where I am)

**Comment by craigpaul** [comment]
Just tagged `v3.0.0-RC1` which adds support for supplying message streams by following the lead of Laravel and Symfony. Please feel free to take it for a spin and send in any issues / PRs needed before a full release can take place 👍
