### ISSUE TITLE
[3.x] Change namespace

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#92]
Current namespace is `Coconuts`.

Proposing to change this to `Craigpaul`.

**Comment by craigpaul** [comment]
100%. Maybe `CraigPaul` specifically, but ya, that's just a relic of how this project initially started 👍

**Comment by mvdnbrk** [comment]
Yeah I am aware of that Paul 😉 

Just created an issue here to keep track of things we might want to change.

**Comment by mvdnbrk** [comment]
Might want to change on packagist as well:

`coconutcraig/laravel-postmark` -> `craigpaul/laravel-postmark`
