### ISSUE TITLE
Postmark webhooks

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#93]
Postmark can call a [webhook](https://postmarkapp.com/email-webhooks) on several events.

I am currently maintaining this package to handle these:
https://github.com/mvdnbrk/laravel-postmark-webhooks

Spatie has also a package which does this for their mailcoach app:
https://github.com/spatie/laravel-mailcoach-postmark-feedback

As part of sending an email you probably want to get notified, now these are separate packages.
Maybe we can integrate these together, one package is easier to maintain and these two complement each other.

**Comment by craigpaul** [comment]
I will take some time to re-review both of these packages. Webhook support within the package itself would be awesome. I like the idea of having it centralized as that would be easier to maintain 👍

**Comment by craigpaul** [comment]
I think I'd personally prefer the package you wrote over the one Spatie has for MailCoach

**Comment by mvdnbrk** [comment]
Thanks :smile:

**Comment by craigpaul** [comment]
I'm going to remove this from the `3.x` milestone as we don't necessarily need this to be ready to go before Laravel 9.0 is released.
