### ISSUE TITLE
Change master branch to main

### ISSUE THREAD

**Issue by mvdnbrk** [coconutcraig/laravel-postmark#96]
See https://github.com/github/renaming

Maybe this is a good point to change the `master` branch to `main`

All breaking changes for the upcoming `3.x` release should go to this branch.

**Comment by mvdnbrk** [comment]
@craigpaul maybe you can create `2.x` branch to target non-breaking changes.

**Comment by craigpaul** [comment]
Good call. I'll do this now.

**Comment by craigpaul** [comment]
Hey @mvdnbrk, this is now complete. It, unfortunately, closed #91 because the destination branch no longer exists.

**Comment by mvdnbrk** [comment]
No problem will fix that
